apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-server.fullname" . }}
  labels:
    app: {{ template "nginx-server.name" . }}
    chart: {{ template "nginx-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "nginx-server.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  type: {{ .Values.service.type }}